vich_uploader:
    db_driver: orm

    mappings:
        paintings:
            uri_prefix: /images/paintings
            upload_destination: '%kernel.project_dir%/assets/images/paintings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        users:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

